# Generated by Django 4.1.2 on 2022-10-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_suggestions_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filedata",
            name="groupname",
        ),
        migrations.RemoveField(
            model_name="imagedata",
            name="groupname",
        ),
    ]
