# Generated by Django 4.1 on 2022-08-27 09:01

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_institusi_users_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationtask',
            name='model',
            field=models.CharField(blank=True, help_text='Selected Model', max_length=50, null=True),
        ),
        migrations.RenameModel(
            old_name='SegmentationData',
            new_name='ImageData',
        ),
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_Images', models.FileField(blank=True, help_text='Image Result', null=True, upload_to=api.models.ResultDataset)),
                ('source', models.ForeignKey(help_text='Corresponding Image Data Source', on_delete=django.db.models.deletion.CASCADE, to='api.imagedata')),
                ('user', models.ForeignKey(help_text='Corresponding user ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='segmentationtask',
            name='result',
            field=models.ForeignKey(help_text='Corresponding Task Result', on_delete=django.db.models.deletion.CASCADE, to='api.resultdata'),
        ),
        migrations.DeleteModel(
            name='SegmentationResult',
        ),
    ]
