# Generated by Django 4.1 on 2022-08-27 09:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_segmentationtask_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationtask',
            name='images',
            field=models.FileField(blank=True, help_text='Image File to be Processed', null=True, upload_to=api.models.ImageDataset),
        ),
    ]
