# Generated by Django 4.1 on 2022-08-31 17:57

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconstructionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, help_text='Task Status', max_length=50, null=True)),
                ('images', models.FileField(blank=True, help_text='Image File to be Processed', null=True, upload_to=api.models.ImageDataset)),
                ('model', models.CharField(blank=True, help_text='Selected Model', max_length=50, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, help_text='Task Creation Date')),
                ('result', models.ForeignKey(help_text='Corresponding Task Result', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resultdata')),
                ('userid', models.ForeignKey(help_text='Corresponding user ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
