# Generated by Django 4.1 on 2022-09-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_reconstructiontask_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationtask',
            name='images',
        ),
    ]
