# Generated by Django 4.1 on 2022-09-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_resultdata_result_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='imageKey',
        ),
        migrations.RemoveField(
            model_name='resultdata',
            name='source',
        ),
    ]
