# Generated by Django 4.1 on 2022-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_taskhistory_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='groupname',
            field=models.CharField(blank=True, help_text='User Group Name for this current Task', max_length=50, null=True),
        ),
    ]
