# Generated by Django 4.1.2 on 2022-10-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_landingpage_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="file",
        ),
    ]
