# Generated by Django 4.1.2 on 2022-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_landingpage_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researcher",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
