# Generated by Django 4.1.2 on 2022-10-20 15:18

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_researcher_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=str,
                        help_text="Publication Name / Synopsis",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        help_text="Publication Link", null=True, verbose_name="link"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Publication Details",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="imagedata",
            name="images",
            field=models.ImageField(
                help_text="Image File to be Processed",
                null=True,
                upload_to=api.models.ImageDataset,
                verbose_name="images",
            ),
        ),
        migrations.AlterField(
            model_name="imagedata",
            name="result",
            field=models.ImageField(
                blank=True,
                help_text="Image Result",
                null=True,
                upload_to=api.models.ResultDataset,
                verbose_name="result",
            ),
        ),
        migrations.CreateModel(
            name="TaskImageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Images",
                    models.ForeignKey(
                        help_text="Corresponding Task Images",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.imagedata",
                        verbose_name="Images",
                    ),
                ),
                (
                    "Task",
                    models.ForeignKey(
                        help_text="Corresponding Task",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.taskhistory",
                        verbose_name="Task",
                    ),
                ),
            ],
        ),
    ]
