# Generated by Django 4.1.2 on 2022-10-23 09:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_publication_alter_imagedata_images_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagedata",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="taskhistory",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="results",
        ),
        migrations.RemoveField(
            model_name="taskhistory",
            name="sources",
        ),
        migrations.AddField(
            model_name="imagedata",
            name="uploaded",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Image Upload Timeframe",
                null=True,
                verbose_name="Uploaded",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="images",
            field=models.ManyToManyField(related_name="image_set", to="api.imagedata"),
        ),
        migrations.AlterField(
            model_name="imagedata",
            name="result",
            field=models.ImageField(
                help_text="Image Result",
                null=True,
                upload_to=api.models.ResultDataset,
                verbose_name="result",
            ),
        ),
        migrations.DeleteModel(
            name="TaskImageMapping",
        ),
    ]
