# Generated by Django 4.1.2 on 2022-10-23 10:56

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_imagedata_options_alter_taskhistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        help_text="User Group Name for this current Task",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        help_text="File to be Processed",
                        null=True,
                        upload_to=api.models.FileDataset,
                        verbose_name="files",
                    ),
                ),
                (
                    "uploaded",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="File Upload Timeframe",
                        null=True,
                        verbose_name="Uploaded",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Corresponding Task",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.taskhistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Corresponding user ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="files",
            field=models.ManyToManyField(related_name="file_set", to="api.filedata"),
        ),
    ]
