# Generated by Django 4.1.2 on 2022-10-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_filedata_taskhistory_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segmentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        help_text="User Group Name for this current Task",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Task Status, ex: 'STARTED', 'FINISHED",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Selected Model for the Task",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "createdate",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Task Creation Date"
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="image_set", to="api.imagedata"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Corresponding user ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Reconstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groupname",
                    models.CharField(
                        help_text="User Group Name for this current Task",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Task Status, ex: 'STARTED', 'FINISHED",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Selected Model for the Task",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "createdate",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Task Creation Date"
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(related_name="file_set", to="api.filedata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Corresponding user ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AlterField(
            model_name="filedata",
            name="task",
            field=models.ForeignKey(
                help_text="Corresponding Task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.reconstruction",
            ),
        ),
        migrations.AlterField(
            model_name="imagedata",
            name="task",
            field=models.ForeignKey(
                help_text="Corresponding Task",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.segmentation",
            ),
        ),
        migrations.DeleteModel(
            name="TaskHistory",
        ),
    ]
