# Generated by Django 4.1 on 2022-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_intuisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='intuisi',
            new_name='institusi',
        ),
    ]
