# Generated by Django 4.1 on 2022-08-10 02:13

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_Images', models.FileField(blank=True, null=True, upload_to=api.models.ResultDataset)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imagedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
