# Generated by Django 4.1 on 2022-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_segmentationtask_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full Name of the User', max_length=50, null=True),
        ),
    ]
