# Generated by Django 4.1 on 2022-09-04 17:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reconstructiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='images',
            field=models.FileField(blank=True, help_text='Image File to be Processed', null=True, upload_to=api.models.ImageDataset, verbose_name='images'),
        ),
    ]
