# Generated by Django 4.1 on 2022-09-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_imagedata_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageList', models.CharField(blank=True, help_text='Image Data Mapping', max_length=50, null=True, verbose_name='imageList')),
                ('user', models.ForeignKey(help_text='Corresponding user ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
