# Generated by Django 4.1 on 2022-09-05 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_userid_segmentationtask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='mapping',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='imageKey',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='imageKey'),
        ),
    ]
