# Generated by Django 4.1.1 on 2022-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_imagedata_groupname"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "section",
                    models.CharField(
                        help_text="Corresponding Landing Page's Section",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Section",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Content of Landing Page's Section",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional Image for Landing Page's Section",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional File for Landing Page's Section",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "link",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional External Link(s) for Landing Page's Section",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
