# Generated by Django 4.1.2 on 2022-10-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_researcher_remove_landingpage_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingpage",
            options={"ordering": ["section"]},
        ),
    ]
