from email.policy import default
from enum import unique
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


def upload_to(instance, filename):  # explicitly set upload path and filename
    return 'images/{user}/{name}'.format(user=instance.user.id, name=filename)


def ImageDataset(instance, filename):  # explicitly set upload path and filename
    return 'imageData/{user}/{name}'.format(user=instance.user.id, name=filename)


def MappingDataset(instance, filename):  # explicitly set upload path and filename
    return 'mappingData/{user}/{name}'.format(user=instance.user.id, name=filename)


def ResultDataset(instance, filename):  # explicitly set upload path and filename
    return 'resultData/{user}/{name}'.format(user=instance.user.id, name=filename)


class Users(AbstractUser):
    full_name = models.CharField(
        max_length=50, blank=True, null=True,  help_text="Full Name of the User")
    avatar = models.ImageField(
        upload_to=upload_to, null=True, blank=True, help_text="Avatar of this user")
    institution = models.CharField(
        max_length=50, null=True, blank=True, help_text="Institution of this user")
    apikey = models.CharField(max_length=50, blank=True, null=True,
                              help_text="User API Key (Token), generated by django AuthToken")


class TaskHistory(models.Model):

    user = models.ForeignKey(
        Users, on_delete=models.CASCADE, help_text="Corresponding user ID")
    groupname = models.CharField(
        max_length=50, null=True, blank=True, help_text="User Group Name for this current Task")
    status = models.CharField(max_length=50, null=True,
                              blank=True, help_text="Task Status, ex: 'STARTED', 'FINISHED")
    model = models.CharField(max_length=50, null=True,
                             blank=True, help_text="Selected Model for the Task")
    type = models.CharField(max_length=50, null=True, blank=True,
                            help_text="Type of the task, ex: 'segmentation'")
    createdate = models.DateTimeField(
        auto_now_add=True, help_text="Task Creation Date")
    sources = models.JSONField(
        _("Source"), default=list, null=True, blank=True, help_text="Source Image's Url(s)")
    results = models.JSONField(
        _("Result"), default=list, null=True, blank=True, help_text="Result Image's Url(s)")


class ImageData(models.Model):
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE, help_text="Corresponding user ID")
    task = models.ForeignKey(TaskHistory, on_delete=models.CASCADE,
                             null=True, blank=True, help_text="Corresponding Task")
    images = models.FileField(_("images"),
                              upload_to=ImageDataset, null=True, blank=True, help_text="Image File to be Processed")
    result = models.ImageField(
        upload_to=ResultDataset, null=True, blank=True, help_text="Image Result")
